language: node_js
node_js:
  - 11.13.0
cache:
  - npm
  - yarn
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of the repository, as a secure variable
  on:
    branch: develop